"""Target-backend intermediate representation for layered FVP portraits.

This module stops deliberately before bytecode emission.  It converts the
editor's character/actor model into an ordered, auditable instruction stream
that a per-game HCB backend can lower later.

The separation is important:

* imported BIN entries describe *what* the body and face resources are;
* a target binding describes *how* one game's dispatcher addresses them;
* stage state describes *where* the actor is and at what final scale;
* the backend owns concrete HCB offsets and opcode encoding.

No function address in this file is assumed to be portable between FVP games.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Iterable, Mapping

from .portrait_project import PortraitProject, PortraitProjectError


PORTRAIT_IR_SCHEMA = "fvp-studio.portrait-ir.v1"


class PortraitCompileError(PortraitProjectError):
    """Raised when a project cannot be lowered for the selected target."""


def _required(value: str, label: str) -> str:
    value = str(value).strip()
    if not value:
        raise PortraitCompileError(f"{label}不能为空")
    return value


@dataclass(frozen=True)
class HoshimemoVariantBinding:
    """Per-variant target-game selector data.

    ``dispatcher_symbol`` identifies the native or private function_4477_
    compatible dispatcher chosen by the Hoshimemo backend.  The four resource
    arguments are emitted as selector/action/outfit/expression.  The expression
    value is deliberately mapped here rather than inferred globally: another
    game may not use face frame numbers as its script selector values.

    ``form_code`` is explicit for the same reason.  Even when two games use
    labels such as L/U/S, their bytecode branches and resource suffixes must be
    profiled independently.
    """

    variant_id: str
    dispatcher_symbol: str
    selector: int
    action_code: int
    outfit_code: int
    form_code: int
    expression_codes: Mapping[str, int] = field(default_factory=dict)
    slot_id: str = ""

    def __post_init__(self) -> None:
        object.__setattr__(self, "variant_id", _required(self.variant_id, "变体 ID"))
        object.__setattr__(
            self,
            "dispatcher_symbol",
            _required(self.dispatcher_symbol, "立绘分派函数符号"),
        )
        object.__setattr__(
            self,
            "expression_codes",
            {str(key): int(value) for key, value in self.expression_codes.items()},
        )
        # Empty keeps backward compatibility with the original per-variant
        # binding.  A non-empty value binds the same imported variant to one
        # exact logical portrait slot, allowing two actors to reuse the same
        # body/face pair through independent dispatchers and primitive pairs.
        object.__setattr__(self, "slot_id", str(self.slot_id).strip())

    def expression_code(self, expression_id: str, frame: int) -> int:
        return int(self.expression_codes.get(expression_id, frame))

    def to_dict(self) -> dict[str, Any]:
        return {
            "variant_id": self.variant_id,
            "dispatcher_symbol": self.dispatcher_symbol,
            "selector": self.selector,
            "action_code": self.action_code,
            "outfit_code": self.outfit_code,
            "form_code": self.form_code,
            "expression_codes": dict(sorted(self.expression_codes.items())),
            "slot_id": self.slot_id,
        }


@dataclass(frozen=True)
class HoshimemoPortraitBackendProfile:
    """Symbolic contract for one profiled Hoshimemo-compatible target.

    Addresses are intentionally absent.  A later bytecode backend must resolve
    these symbols against a fingerprinted HCB profile before writing anything.
    """

    profile_id: str
    portrait_abi: str = "resource4_runtime9"
    apply_layout_symbol: str = "function_4480_"
    # Private helper generated by the byte emitter.  It follows the original
    # function_4477_ registration path and applies one complete *static*
    # primitive state through function_4286_ + PrimSet* direct setters.
    # MotionMove* remains a separate ABI for future animated transitions.
    final_transform_symbol: str = "native_primitive_state"
    opacity_symbol: str = "function_4405_"
    rotation_symbol: str = "function_4409_"
    expression_update_symbol: str = "function_4487_compatible"
    geometry_xy_symbol: str = "function_4406_"
    geometry_z_symbol: str = "function_4407_"
    geometry_scale_symbol: str = "function_4408_"

    def __post_init__(self) -> None:
        object.__setattr__(self, "profile_id", _required(self.profile_id, "目标配置 ID"))
        if self.portrait_abi not in {"resource4_runtime8", "resource4_runtime9"}:
            raise PortraitCompileError("当前 IR 只支持已研究的 4+8 / 4+9 立绘 ABI")
        for label, value in (
            ("布局函数符号", self.apply_layout_symbol),
            ("最终变换函数符号", self.final_transform_symbol),
            ("透明度函数符号", self.opacity_symbol),
            ("旋转函数符号", self.rotation_symbol),
            ("表情更新函数符号", self.expression_update_symbol),
            ("XY 几何函数符号", self.geometry_xy_symbol),
            ("Z 几何函数符号", self.geometry_z_symbol),
            ("缩放几何函数符号", self.geometry_scale_symbol),
        ):
            _required(value, label)

    def to_dict(self) -> dict[str, str]:
        return {
            "profile_id": self.profile_id,
            "portrait_abi": self.portrait_abi,
            "apply_layout_symbol": self.apply_layout_symbol,
            "final_transform_symbol": self.final_transform_symbol,
            "opacity_symbol": self.opacity_symbol,
            "rotation_symbol": self.rotation_symbol,
            "expression_update_symbol": self.expression_update_symbol,
            "geometry_xy_symbol": self.geometry_xy_symbol,
            "geometry_z_symbol": self.geometry_z_symbol,
            "geometry_scale_symbol": self.geometry_scale_symbol,
        }


@dataclass(frozen=True)
class PortraitIROperation:
    kind: str
    payload: Mapping[str, Any]

    def __post_init__(self) -> None:
        object.__setattr__(self, "kind", _required(self.kind, "IR 操作类型"))
        object.__setattr__(self, "payload", dict(self.payload))

    def to_dict(self) -> dict[str, Any]:
        return {"kind": self.kind, "payload": dict(self.payload)}


@dataclass(frozen=True)
class PortraitIRProgram:
    target_profile: HoshimemoPortraitBackendProfile
    operations: tuple[PortraitIROperation, ...]
    warnings: tuple[str, ...] = ()

    def to_dict(self) -> dict[str, Any]:
        return {
            "schema": PORTRAIT_IR_SCHEMA,
            "target_profile": self.target_profile.to_dict(),
            "operations": [operation.to_dict() for operation in self.operations],
            "warnings": list(self.warnings),
        }


def _binding_index(
    bindings: Iterable[HoshimemoVariantBinding],
) -> dict[tuple[str, str], HoshimemoVariantBinding]:
    result: dict[tuple[str, str], HoshimemoVariantBinding] = {}
    for binding in bindings:
        key = (binding.variant_id, binding.slot_id)
        if key in result:
            suffix = f"/{binding.slot_id}" if binding.slot_id else "/<默认>"
            raise PortraitCompileError(
                f"重复的目标变体绑定: {binding.variant_id}{suffix}"
            )
        result[key] = binding
    return result


def _resolved_actor_and_binding(
    project: PortraitProject,
    actor_id: str,
    bindings: Mapping[tuple[str, str], HoshimemoVariantBinding],
) -> tuple[dict[str, Any], HoshimemoVariantBinding]:
    resolved = project.resolve_actor(actor_id)
    variant_id = str(resolved["variant_id"])
    slot_id = str(resolved["slot_id"])
    binding = bindings.get((variant_id, slot_id))
    if binding is None:
        binding = bindings.get((variant_id, ""))
    if binding is None:
        raise PortraitCompileError(
            f"变体 {variant_id} 在立绘槽 {slot_id} "
            "尚未分配目标游戏资源选择器/包装函数"
        )
    return resolved, binding


def _register_operation(
    resolved: Mapping[str, Any],
    binding: HoshimemoVariantBinding,
    profile: HoshimemoPortraitBackendProfile,
) -> PortraitIROperation:
    expression_code = binding.expression_code(
        str(resolved["expression_id"]), int(resolved["face_frame"])
    )
    transform = dict(resolved["transform"])
    # This is the verified high-level Hoshimemo call shape.  It is still IR:
    # the bytecode backend must encode values and resolve dispatcher_symbol.
    resource_args = (
        binding.selector,
        binding.action_code,
        binding.outfit_code,
        expression_code,
    )
    runtime_prefix = (
        binding.form_code,
        int(resolved["position_preset"]),
        None,
        int(transform["z"]),
        int(transform["x"]),
        int(transform["y"]),
    )
    if profile.portrait_abi == "resource4_runtime9":
        runtime_args = (
            *runtime_prefix,
            # Rotation is deliberately not duplicated in the registration ABI.
            # The explicit static-state operation below owns the final angle.
            None,
            int(resolved["state_slot"]),
            resolved["transition"],
        )
    elif profile.portrait_abi == "resource4_runtime8":
        # Older FVP dispatchers expose the same resource and geometry fields
        # without the otherwise-unused registration rotation placeholder.
        runtime_args = (
            *runtime_prefix,
            int(resolved["state_slot"]),
            resolved["transition"],
        )
    else:  # pragma: no cover - guarded by the frozen profile dataclass
        raise PortraitCompileError(f"不支持的立绘 ABI: {profile.portrait_abi}")
    return PortraitIROperation(
        "register_actor",
        {
            "actor_id": resolved["actor_id"],
            "variant_id": resolved["variant_id"],
            "pose_id": resolved["pose_id"],
            "form_id": resolved["form_id"],
            "expression_id": resolved["expression_id"],
            "body": resolved["body"],
            "face": resolved["face"],
            "face_frame": resolved["face_frame"],
            "face_offset": resolved["face_offset"],
            "dispatcher_symbol": binding.dispatcher_symbol,
            "resource_args": list(resource_args),
            "runtime_args": list(runtime_args),
            "state_slot": resolved["state_slot"],
            "slot_id": resolved["slot_id"],
        },
    )


def _final_transform_operation(
    resolved: Mapping[str, Any],
    profile: HoshimemoPortraitBackendProfile,
) -> PortraitIROperation:
    transform = dict(resolved["transform"])
    rotation_degrees = int(transform["rotation"])
    rotation_tenths = rotation_degrees * 10
    if not -32768 <= rotation_tenths <= 32767:
        raise PortraitCompileError("立绘旋转角度无法编码为十分之一度")
    return PortraitIROperation(
        "apply_final_transform",
        {
            "actor_id": resolved["actor_id"],
            "state_slot": resolved["state_slot"],
            "slot_id": resolved["slot_id"],
            "setter_symbol": profile.final_transform_symbol,
            "transform": {
                key: int(transform[key])
                for key in ("x", "y", "z", "scale", "rotation", "opacity")
            },
            "rotation_tenths": rotation_tenths,
            "mode": "direct_static_state",
            "ordering": "after_native_layout",
        },
    )


def _actor_finish_operations(
    resolved: Mapping[str, Any],
    profile: HoshimemoPortraitBackendProfile,
) -> tuple[PortraitIROperation, ...]:
    return (_final_transform_operation(resolved, profile),)


def compile_stage_snapshot(
    project: PortraitProject,
    profile: HoshimemoPortraitBackendProfile,
    bindings: Iterable[HoshimemoVariantBinding],
    *,
    apply_duration: int | None = 0,
) -> PortraitIRProgram:
    """Compile all visible actors in the safe four-phase order.

    1. Register every body + attached expression pair.
    2. Invoke the target game's native multi-actor layout/apply helper once.
    3. Reapply each user's complete static X/Y/Z/scale/rotation/opacity state
       through the original direct-set path used by function_4477_.

    Keeping the third phase last prevents native layout from silently moving a
    manually calibrated actor after an expression/action update.  Animated
    MotionMove* calls are intentionally not used as static setters here.
    """

    project.validate()
    binding_map = _binding_index(bindings)
    actor_ids = [
        actor_id
        for actor_id, actor in project.actors.items()
        if not actor.hidden
    ]
    operations: list[PortraitIROperation] = []
    resolved_actors: list[dict[str, Any]] = []
    for actor_id in actor_ids:
        resolved, binding = _resolved_actor_and_binding(project, actor_id, binding_map)
        resolved_actors.append(resolved)
        operations.append(_register_operation(resolved, binding, profile))
    if resolved_actors:
        operations.append(
            PortraitIROperation(
                "apply_native_layout",
                {
                    "symbol": profile.apply_layout_symbol,
                    "duration": apply_duration,
                    "actor_ids": [item["actor_id"] for item in resolved_actors],
                    "registered_before_apply": True,
                },
            )
        )
        for resolved in resolved_actors:
            operations.extend(_actor_finish_operations(resolved, profile))
    return PortraitIRProgram(profile, tuple(operations))


def compile_expression_update(
    project: PortraitProject,
    profile: HoshimemoPortraitBackendProfile,
    bindings: Iterable[HoshimemoVariantBinding],
    actor_id: str,
) -> PortraitIRProgram:
    """Compile a face-only update with an explicit transform-preservation guard."""

    project.validate()
    resolved, binding = _resolved_actor_and_binding(
        project, actor_id, _binding_index(bindings)
    )
    expression_code = binding.expression_code(
        str(resolved["expression_id"]), int(resolved["face_frame"])
    )
    operations = (
        PortraitIROperation(
            "update_expression",
            {
                "actor_id": resolved["actor_id"],
                "variant_id": resolved["variant_id"],
                "face": resolved["face"],
                "face_frame": resolved["face_frame"],
                "expression_id": resolved["expression_id"],
                "expression_code": expression_code,
                "state_slot": resolved["state_slot"],
                "slot_id": resolved["slot_id"],
                "symbol": profile.expression_update_symbol,
                "body_must_remain": resolved["body"],
                "preserve_transform": True,
            },
        ),
        *_actor_finish_operations(resolved, profile),
    )
    return PortraitIRProgram(profile, operations)


def compile_variant_update(
    project: PortraitProject,
    profile: HoshimemoPortraitBackendProfile,
    bindings: Iterable[HoshimemoVariantBinding],
    actor_id: str,
    *,
    apply_duration: int | None = 0,
) -> PortraitIRProgram:
    """Compile an atomic body/action + attached expression-group update."""

    project.validate()
    resolved, binding = _resolved_actor_and_binding(
        project, actor_id, _binding_index(bindings)
    )
    operations = (
        _register_operation(resolved, binding, profile),
        PortraitIROperation(
            "apply_native_layout",
            {
                "symbol": profile.apply_layout_symbol,
                "duration": apply_duration,
                "actor_ids": [actor_id],
                "registered_before_apply": True,
            },
        ),
        *_actor_finish_operations(resolved, profile),
    )
    return PortraitIRProgram(profile, operations)
